// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/models/shared"
	"net/http"
)

type CreateProductRecommendationResponse struct {
	// Any error based on client data errors
	ClientError *shared.ClientError
	// HTTP response content type for this operation
	ContentType string
	// Product recommendations request payload
	ProductRecommendation *shared.ProductRecommendation
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *CreateProductRecommendationResponse) GetClientError() *shared.ClientError {
	if c == nil {
		return nil
	}
	return c.ClientError
}

func (c *CreateProductRecommendationResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateProductRecommendationResponse) GetProductRecommendation() *shared.ProductRecommendation {
	if c == nil {
		return nil
	}
	return c.ProductRecommendation
}

func (c *CreateProductRecommendationResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateProductRecommendationResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}
