// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/models/shared"
	"net/http"
)

type CreatePortalPageBlockRequest struct {
	// The portal page block to create
	BlockRequest shared.BlockRequest `request:"mediaType=application/json"`
	ID           string              `pathParam:"style=simple,explode=false,name=id"`
}

func (o *CreatePortalPageBlockRequest) GetBlockRequest() shared.BlockRequest {
	if o == nil {
		return shared.BlockRequest{}
	}
	return o.BlockRequest
}

func (o *CreatePortalPageBlockRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type CreatePortalPageBlockResponse struct {
	// The portal page block has been created successfully.
	Block *shared.Block
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreatePortalPageBlockResponse) GetBlock() *shared.Block {
	if o == nil {
		return nil
	}
	return o.Block
}

func (o *CreatePortalPageBlockResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreatePortalPageBlockResponse) GetErrorResp() *shared.ErrorResp {
	if o == nil {
		return nil
	}
	return o.ErrorResp
}

func (o *CreatePortalPageBlockResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreatePortalPageBlockResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
