// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/models/shared"
	"net/http"
)

type DeleteProductRequest struct {
	// The product id
	ProductID string `pathParam:"style=simple,explode=false,name=productId"`
}

func (d *DeleteProductRequest) GetProductID() string {
	if d == nil {
		return ""
	}
	return d.ProductID
}

type DeleteProductResponse struct {
	// Any error based on client data errors
	ClientError *shared.ClientError
	// HTTP response content type for this operation
	ContentType string
	// Product entity response
	Product *shared.Product
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteProductResponse) GetClientError() *shared.ClientError {
	if d == nil {
		return nil
	}
	return d.ClientError
}

func (d *DeleteProductResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteProductResponse) GetProduct() *shared.Product {
	if d == nil {
		return nil
	}
	return d.Product
}

func (d *DeleteProductResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteProductResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
