// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/models/shared"
	"net/http"
)

type GetOpportunityRequest struct {
	// The ID of opportunity
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetOpportunityRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetOpportunityResponseBody - The returned opportunities
type GetOpportunityResponseBody struct {
	// The opportunity entity
	Entity *shared.Opportunity `json:"entity,omitempty"`
	// The related files of the requested opportunity
	Files          []shared.File           `json:"files,omitempty"`
	JourneyActions []shared.JourneyActions `json:"journey_actions,omitempty"`
	// The related orders of the requested opportunity
	Orders []shared.Order `json:"orders,omitempty"`
	// The related entities of the requested opportunity
	Relations []shared.EntityItem `json:"relations,omitempty"`
	// The related workflows of the requested opportunity
	Workflow []map[string]any `json:"workflow,omitempty"`
}

func (o *GetOpportunityResponseBody) GetEntity() *shared.Opportunity {
	if o == nil {
		return nil
	}
	return o.Entity
}

func (o *GetOpportunityResponseBody) GetFiles() []shared.File {
	if o == nil {
		return nil
	}
	return o.Files
}

func (o *GetOpportunityResponseBody) GetJourneyActions() []shared.JourneyActions {
	if o == nil {
		return nil
	}
	return o.JourneyActions
}

func (o *GetOpportunityResponseBody) GetOrders() []shared.Order {
	if o == nil {
		return nil
	}
	return o.Orders
}

func (o *GetOpportunityResponseBody) GetRelations() []shared.EntityItem {
	if o == nil {
		return nil
	}
	return o.Relations
}

func (o *GetOpportunityResponseBody) GetWorkflow() []map[string]any {
	if o == nil {
		return nil
	}
	return o.Workflow
}

type GetOpportunityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The returned opportunities
	Object *GetOpportunityResponseBody
}

func (o *GetOpportunityResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetOpportunityResponse) GetErrorResp() *shared.ErrorResp {
	if o == nil {
		return nil
	}
	return o.ErrorResp
}

func (o *GetOpportunityResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetOpportunityResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetOpportunityResponse) GetObject() *GetOpportunityResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
