// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/models/shared"
	"net/http"
)

type GetOrderRequest struct {
	// The ID of order
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetOrderRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetOrderResponseBody - The requested order has been retrieved successfully.
type GetOrderResponseBody struct {
	// The related cross sellable products of the requested order
	CrossSellableProducts []shared.Product `json:"crossSellableProducts,omitempty"`
	// The order entity
	Entity *shared.Order `json:"entity,omitempty"`
	// The related files of the requested order
	Files          []shared.File           `json:"files,omitempty"`
	JourneyActions []shared.JourneyActions `json:"journey_actions,omitempty"`
	// The related products of the requested order
	Products []shared.Product `json:"products,omitempty"`
	// The related entities of the requested order
	Relations []shared.EntityItem `json:"relations,omitempty"`
	// The related workflows of the requested order
	Workflow []map[string]any `json:"workflow,omitempty"`
}

func (o *GetOrderResponseBody) GetCrossSellableProducts() []shared.Product {
	if o == nil {
		return nil
	}
	return o.CrossSellableProducts
}

func (o *GetOrderResponseBody) GetEntity() *shared.Order {
	if o == nil {
		return nil
	}
	return o.Entity
}

func (o *GetOrderResponseBody) GetFiles() []shared.File {
	if o == nil {
		return nil
	}
	return o.Files
}

func (o *GetOrderResponseBody) GetJourneyActions() []shared.JourneyActions {
	if o == nil {
		return nil
	}
	return o.JourneyActions
}

func (o *GetOrderResponseBody) GetProducts() []shared.Product {
	if o == nil {
		return nil
	}
	return o.Products
}

func (o *GetOrderResponseBody) GetRelations() []shared.EntityItem {
	if o == nil {
		return nil
	}
	return o.Relations
}

func (o *GetOrderResponseBody) GetWorkflow() []map[string]any {
	if o == nil {
		return nil
	}
	return o.Workflow
}

type GetOrderResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested order has been retrieved successfully.
	Object *GetOrderResponseBody
}

func (o *GetOrderResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetOrderResponse) GetErrorResp() *shared.ErrorResp {
	if o == nil {
		return nil
	}
	return o.ErrorResp
}

func (o *GetOrderResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetOrderResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetOrderResponse) GetObject() *GetOrderResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
