// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/models/shared"
	"net/http"
)

type GetOrganizationSettingsByDomainRequest struct {
	Domain string `queryParam:"style=form,explode=true,name=domain"`
}

func (o *GetOrganizationSettingsByDomainRequest) GetDomain() string {
	if o == nil {
		return ""
	}
	return o.Domain
}

// GetOrganizationSettingsByDomainResponseBody - Retrieved organization settings successfully.
type GetOrganizationSettingsByDomainResponseBody struct {
	Data *shared.OrganizationSettings `json:"data,omitempty"`
}

func (o *GetOrganizationSettingsByDomainResponseBody) GetData() *shared.OrganizationSettings {
	if o == nil {
		return nil
	}
	return o.Data
}

type GetOrganizationSettingsByDomainResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Internal Server Error
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Retrieved organization settings successfully.
	Object *GetOrganizationSettingsByDomainResponseBody
}

func (o *GetOrganizationSettingsByDomainResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetOrganizationSettingsByDomainResponse) GetErrorResp() *shared.ErrorResp {
	if o == nil {
		return nil
	}
	return o.ErrorResp
}

func (o *GetOrganizationSettingsByDomainResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetOrganizationSettingsByDomainResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetOrganizationSettingsByDomainResponse) GetObject() *GetOrganizationSettingsByDomainResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
