// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/models/shared"
	"net/http"
)

type GetPortalPageBlocksRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetPortalPageBlocksRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetPortalPageBlocksResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The portal page blocks have been fetched successfully.
	Classes []shared.Block
}

func (o *GetPortalPageBlocksResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetPortalPageBlocksResponse) GetErrorResp() *shared.ErrorResp {
	if o == nil {
		return nil
	}
	return o.ErrorResp
}

func (o *GetPortalPageBlocksResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetPortalPageBlocksResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetPortalPageBlocksResponse) GetClasses() []shared.Block {
	if o == nil {
		return nil
	}
	return o.Classes
}
