// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/models/shared"
	"net/http"
)

type GetResolvedExternalLinkRequest struct {
	// Contact ID of the user
	ContactID *string `queryParam:"style=form,explode=true,name=contactId"`
	// ID of the External Link
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Origin of the portal
	Origin *string `queryParam:"style=form,explode=true,name=origin"`
}

func (o *GetResolvedExternalLinkRequest) GetContactID() *string {
	if o == nil {
		return nil
	}
	return o.ContactID
}

func (o *GetResolvedExternalLinkRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetResolvedExternalLinkRequest) GetOrigin() *string {
	if o == nil {
		return nil
	}
	return o.Origin
}

type GetResolvedExternalLinkResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// Resolved portal config link retrieved successfully.
	ExternalLink *shared.ExternalLink
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetResolvedExternalLinkResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetResolvedExternalLinkResponse) GetErrorResp() *shared.ErrorResp {
	if o == nil {
		return nil
	}
	return o.ErrorResp
}

func (o *GetResolvedExternalLinkResponse) GetExternalLink() *shared.ExternalLink {
	if o == nil {
		return nil
	}
	return o.ExternalLink
}

func (o *GetResolvedExternalLinkResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetResolvedExternalLinkResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
