// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/models/shared"
	"net/http"
)

type GetSearchableAttributesForOpportunitiesRequest struct {
	From *float64 `default:"0" queryParam:"style=form,explode=true,name=from"`
	Size *float64 `default:"1000" queryParam:"style=form,explode=true,name=size"`
}

func (g GetSearchableAttributesForOpportunitiesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSearchableAttributesForOpportunitiesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *GetSearchableAttributesForOpportunitiesRequest) GetFrom() *float64 {
	if o == nil {
		return nil
	}
	return o.From
}

func (o *GetSearchableAttributesForOpportunitiesRequest) GetSize() *float64 {
	if o == nil {
		return nil
	}
	return o.Size
}

// GetSearchableAttributesForOpportunitiesResponseBody - The opportunities is retrieved successfully for the portal user.
type GetSearchableAttributesForOpportunitiesResponseBody struct {
	Data []shared.Opportunity `json:"data,omitempty"`
}

func (o *GetSearchableAttributesForOpportunitiesResponseBody) GetData() []shared.Opportunity {
	if o == nil {
		return nil
	}
	return o.Data
}

type GetSearchableAttributesForOpportunitiesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The opportunities is retrieved successfully for the portal user.
	Object *GetSearchableAttributesForOpportunitiesResponseBody
}

func (o *GetSearchableAttributesForOpportunitiesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSearchableAttributesForOpportunitiesResponse) GetErrorResp() *shared.ErrorResp {
	if o == nil {
		return nil
	}
	return o.ErrorResp
}

func (o *GetSearchableAttributesForOpportunitiesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSearchableAttributesForOpportunitiesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetSearchableAttributesForOpportunitiesResponse) GetObject() *GetSearchableAttributesForOpportunitiesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
