// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/models/shared"
	"net/http"
)

type Resource struct {
	AdditionalProperties any `additionalProperties:"true" json:"-"`
	// Contact
	Contact *string `json:"contact,omitempty"`
	// Description
	Description *string `json:"description,omitempty"`
	// Kind
	Kind *string `json:"kind,omitempty"`
	// Resource ID
	ResourceID *string `json:"resource_id,omitempty"`
}

func (r Resource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Resource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *Resource) GetAdditionalProperties() any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *Resource) GetContact() *string {
	if o == nil {
		return nil
	}
	return o.Contact
}

func (o *Resource) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Resource) GetKind() *string {
	if o == nil {
		return nil
	}
	return o.Kind
}

func (o *Resource) GetResourceID() *string {
	if o == nil {
		return nil
	}
	return o.ResourceID
}

type NotifyMLoginInterestChangeRequestBody struct {
	AdditionalProperties any `additionalProperties:"true" json:"-"`
	// Action
	Action *string `json:"action,omitempty"`
	// Interest tag
	InterestTag *string   `json:"interest_tag,omitempty"`
	Resource    *Resource `json:"resource,omitempty"`
	// Resource ID
	ResourceID *string `json:"resource_id,omitempty"`
	// Resource type
	UserID *string `json:"user_id,omitempty"`
}

func (n NotifyMLoginInterestChangeRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NotifyMLoginInterestChangeRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *NotifyMLoginInterestChangeRequestBody) GetAdditionalProperties() any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *NotifyMLoginInterestChangeRequestBody) GetAction() *string {
	if o == nil {
		return nil
	}
	return o.Action
}

func (o *NotifyMLoginInterestChangeRequestBody) GetInterestTag() *string {
	if o == nil {
		return nil
	}
	return o.InterestTag
}

func (o *NotifyMLoginInterestChangeRequestBody) GetResource() *Resource {
	if o == nil {
		return nil
	}
	return o.Resource
}

func (o *NotifyMLoginInterestChangeRequestBody) GetResourceID() *string {
	if o == nil {
		return nil
	}
	return o.ResourceID
}

func (o *NotifyMLoginInterestChangeRequestBody) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

type NotifyMLoginInterestChangeRequest struct {
	RequestBody NotifyMLoginInterestChangeRequestBody `request:"mediaType=application/json"`
	// Client ID
	ClientID string `pathParam:"style=simple,explode=false,name=client_id"`
	// User ID
	UserID string `pathParam:"style=simple,explode=false,name=user_id"`
}

func (o *NotifyMLoginInterestChangeRequest) GetRequestBody() NotifyMLoginInterestChangeRequestBody {
	if o == nil {
		return NotifyMLoginInterestChangeRequestBody{}
	}
	return o.RequestBody
}

func (o *NotifyMLoginInterestChangeRequest) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *NotifyMLoginInterestChangeRequest) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

type NotifyMLoginInterestChangeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *NotifyMLoginInterestChangeResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *NotifyMLoginInterestChangeResponse) GetErrorResp() *shared.ErrorResp {
	if o == nil {
		return nil
	}
	return o.ErrorResp
}

func (o *NotifyMLoginInterestChangeResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *NotifyMLoginInterestChangeResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
