// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/models/shared"
	"net/http"
)

type PostOrderAcceptanceRequest struct {
	AcceptanceDecision *shared.AcceptanceDecision `request:"mediaType=application/json"`
	// The ID of order
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *PostOrderAcceptanceRequest) GetAcceptanceDecision() *shared.AcceptanceDecision {
	if o == nil {
		return nil
	}
	return o.AcceptanceDecision
}

func (o *PostOrderAcceptanceRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// PostOrderAcceptanceResponseBody - Order was accepted/declined successfully.
type PostOrderAcceptanceResponseBody struct {
	// The order entity
	Data *shared.Order `json:"data,omitempty"`
}

func (o *PostOrderAcceptanceResponseBody) GetData() *shared.Order {
	if o == nil {
		return nil
	}
	return o.Data
}

type PostOrderAcceptanceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Order was accepted/declined successfully.
	Object *PostOrderAcceptanceResponseBody
}

func (o *PostOrderAcceptanceResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostOrderAcceptanceResponse) GetErrorResp() *shared.ErrorResp {
	if o == nil {
		return nil
	}
	return o.ErrorResp
}

func (o *PostOrderAcceptanceResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostOrderAcceptanceResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PostOrderAcceptanceResponse) GetObject() *PostOrderAcceptanceResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
