// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/models/shared"
	"net/http"
)

type PutPortalConfigRequest struct {
	// Portal configuration payload
	PortalConfigV3 shared.PortalConfigV3 `request:"mediaType=application/json"`
	// Portal ID (readonly UUID generated on portal creation)
	PortalID string `pathParam:"style=simple,explode=false,name=portal_id"`
}

func (o *PutPortalConfigRequest) GetPortalConfigV3() shared.PortalConfigV3 {
	if o == nil {
		return shared.PortalConfigV3{}
	}
	return o.PortalConfigV3
}

func (o *PutPortalConfigRequest) GetPortalID() string {
	if o == nil {
		return ""
	}
	return o.PortalID
}

type PutPortalConfigResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The request could not be validated
	ErrorResp *shared.ErrorResp
	// Portal config updated successfully.
	PortalConfigV3 *shared.PortalConfigV3
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PutPortalConfigResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutPortalConfigResponse) GetErrorResp() *shared.ErrorResp {
	if o == nil {
		return nil
	}
	return o.ErrorResp
}

func (o *PutPortalConfigResponse) GetPortalConfigV3() *shared.PortalConfigV3 {
	if o == nil {
		return nil
	}
	return o.PortalConfigV3
}

func (o *PutPortalConfigResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutPortalConfigResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
