// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/models/shared"
	"net/http"
)

type SsoCallbackRequest struct {
	SSOCallbackRequest shared.SSOCallbackRequest `request:"mediaType=application/json"`
	Domain             *string                   `queryParam:"style=form,explode=true,name=domain"`
}

func (o *SsoCallbackRequest) GetSSOCallbackRequest() shared.SSOCallbackRequest {
	if o == nil {
		return shared.SSOCallbackRequest{}
	}
	return o.SSOCallbackRequest
}

func (o *SsoCallbackRequest) GetDomain() *string {
	if o == nil {
		return nil
	}
	return o.Domain
}

type SsoCallbackResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Internal Server Error
	ErrorResp *shared.ErrorResp
	// The token to be used with the CUSTOM_AUTH flow against Cognito
	SSOCallbackResponse *shared.SSOCallbackResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *SsoCallbackResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SsoCallbackResponse) GetErrorResp() *shared.ErrorResp {
	if o == nil {
		return nil
	}
	return o.ErrorResp
}

func (o *SsoCallbackResponse) GetSSOCallbackResponse() *shared.SSOCallbackResponse {
	if o == nil {
		return nil
	}
	return o.SSOCallbackResponse
}

func (o *SsoCallbackResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SsoCallbackResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
