// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/models/shared"
	"net/http"
)

type UpdateProductRecommendationRequest struct {
	// Product recommendation to update
	ProductRecommendationCreate shared.ProductRecommendationCreate `request:"mediaType=application/json"`
	// The product recommendation id
	ProductRecommendationID string `pathParam:"style=simple,explode=false,name=productRecommendationId"`
}

func (u *UpdateProductRecommendationRequest) GetProductRecommendationCreate() shared.ProductRecommendationCreate {
	if u == nil {
		return shared.ProductRecommendationCreate{}
	}
	return u.ProductRecommendationCreate
}

func (u *UpdateProductRecommendationRequest) GetProductRecommendationID() string {
	if u == nil {
		return ""
	}
	return u.ProductRecommendationID
}

type UpdateProductRecommendationResponse struct {
	// Any error based on client data errors
	ClientError *shared.ClientError
	// HTTP response content type for this operation
	ContentType string
	// Product recommendations request payload
	ProductRecommendation *shared.ProductRecommendation
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (u *UpdateProductRecommendationResponse) GetClientError() *shared.ClientError {
	if u == nil {
		return nil
	}
	return u.ClientError
}

func (u *UpdateProductRecommendationResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateProductRecommendationResponse) GetProductRecommendation() *shared.ProductRecommendation {
	if u == nil {
		return nil
	}
	return u.ProductRecommendation
}

func (u *UpdateProductRecommendationResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateProductRecommendationResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}
