// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/models/shared"
	"net/http"
)

type UpdatePriceRequest struct {
	// Price to update
	PriceCreate shared.PriceCreate `request:"mediaType=application/json"`
	// The price id
	PriceID string `pathParam:"style=simple,explode=false,name=priceId"`
}

func (u *UpdatePriceRequest) GetPriceCreate() shared.PriceCreate {
	if u == nil {
		return shared.PriceCreate{}
	}
	return u.PriceCreate
}

func (u *UpdatePriceRequest) GetPriceID() string {
	if u == nil {
		return ""
	}
	return u.PriceID
}

type UpdatePriceResponse struct {
	// Any error based on client data errors
	ClientError *shared.ClientError
	// HTTP response content type for this operation
	ContentType string
	// Price entity with id
	Price *shared.Price
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (u *UpdatePriceResponse) GetClientError() *shared.ClientError {
	if u == nil {
		return nil
	}
	return u.ClientError
}

func (u *UpdatePriceResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdatePriceResponse) GetPrice() *shared.Price {
	if u == nil {
		return nil
	}
	return u.Price
}

func (u *UpdatePriceResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdatePriceResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}
