// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/internal/utils"
)

type BlockRequest struct {
	AdditionalProperties any `additionalProperties:"true" json:"-"`
	// The order of the block
	Order float64 `json:"order"`
	// The id of the parent block
	ParentID *string     `json:"parentId,omitempty"`
	Props    *BlockProps `json:"props,omitempty"`
	// The type of the block. eg; tabs, tab, group, attribute
	Type string `json:"type"`
}

func (b BlockRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BlockRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"order", "type"}); err != nil {
		return err
	}
	return nil
}

func (o *BlockRequest) GetAdditionalProperties() any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *BlockRequest) GetOrder() float64 {
	if o == nil {
		return 0.0
	}
	return o.Order
}

func (o *BlockRequest) GetParentID() *string {
	if o == nil {
		return nil
	}
	return o.ParentID
}

func (o *BlockRequest) GetProps() *BlockProps {
	if o == nil {
		return nil
	}
	return o.Props
}

func (o *BlockRequest) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}
