// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/internal/utils"
	"time"
)

type ContactSchema string

const (
	ContactSchemaContact ContactSchema = "contact"
)

func (e ContactSchema) ToPointer() *ContactSchema {
	return &e
}
func (e *ContactSchema) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "contact":
		*e = ContactSchema(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ContactSchema: %v", v)
	}
}

// Contact - The mapped contact of the portal user
type Contact struct {
	AdditionalProperties any `additionalProperties:"true" json:"-"`
	// Creation timestamp of the entity
	CreatedAt time.Time `json:"_created_at"`
	// Entity ID
	ID string `json:"_id"`
	// Organization ID the entity belongs to
	Org    string        `json:"_org"`
	Schema ContactSchema `json:"_schema"`
	// Array of entity tags
	Tags []string `json:"_tags,omitempty"`
	// Title of the entity
	Title string `json:"_title"`
	// Last update timestamp of the entity
	UpdatedAt time.Time `json:"_updated_at"`
}

func (c Contact) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Contact) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"_created_at", "_id", "_org", "_schema", "_title", "_updated_at"}); err != nil {
		return err
	}
	return nil
}

func (o *Contact) GetAdditionalProperties() any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *Contact) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *Contact) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Contact) GetOrg() string {
	if o == nil {
		return ""
	}
	return o.Org
}

func (o *Contact) GetSchema() ContactSchema {
	if o == nil {
		return ContactSchema("")
	}
	return o.Schema
}

func (o *Contact) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *Contact) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *Contact) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
