// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/internal/utils"
	"time"
)

type Schema string

const (
	SchemaCoupon Schema = "coupon"
)

func (e Schema) ToPointer() *Schema {
	return &e
}
func (e *Schema) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "coupon":
		*e = Schema(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Schema: %v", v)
	}
}

// CashbackPeriod - The cashback period, for now it's limited to either 0 months or 12 months
type CashbackPeriod string

const (
	CashbackPeriodZero   CashbackPeriod = "0"
	CashbackPeriodTwelve CashbackPeriod = "12"
)

func (e CashbackPeriod) ToPointer() *CashbackPeriod {
	return &e
}
func (e *CashbackPeriod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "0":
		fallthrough
	case "12":
		*e = CashbackPeriod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CashbackPeriod: %v", v)
	}
}

type Category string

const (
	CategoryDiscount Category = "discount"
	CategoryCashback Category = "cashback"
)

func (e Category) ToPointer() *Category {
	return &e
}
func (e *Category) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "discount":
		fallthrough
	case "cashback":
		*e = Category(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Category: %v", v)
	}
}

type Type string

const (
	TypeFixed      Type = "fixed"
	TypePercentage Type = "percentage"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "fixed":
		fallthrough
	case "percentage":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type Coupon struct {
	// Additional fields that are not part of the schema
	Additional map[string]any `json:"__additional,omitempty"`
	// Access control list (ACL) for an entity. Defines sharing access to external orgs or users.
	ACL       *BaseEntityACL `json:"_acl,omitempty"`
	CreatedAt *time.Time     `json:"_created_at,omitempty"`
	Files     *BaseRelation  `json:"_files,omitempty"`
	ID        *string        `json:"_id,omitempty"`
	// Manifest ID used to create/update the entity
	Manifest []string `json:"_manifest,omitempty"`
	// Organization Id the entity belongs to
	Org       string            `json:"_org"`
	Owners    []BaseEntityOwner `json:"_owners,omitempty"`
	Schema    Schema            `json:"_schema"`
	Tags      []string          `json:"_tags,omitempty"`
	Title     *string           `json:"_title,omitempty"`
	UpdatedAt *time.Time        `json:"_updated_at,omitempty"`
	Active    bool              `json:"active"`
	// The cashback period, for now it's limited to either 0 months or 12 months
	CashbackPeriod *CashbackPeriod `json:"cashback_period,omitempty"`
	Category       Category        `json:"category"`
	Description    *string         `json:"description,omitempty"`
	// Use if type is set to fixed. The fixed amount in cents to be discounted, represented as a whole integer.
	FixedValue *float64 `json:"fixed_value,omitempty"`
	// Use if type is set to fixed. Three-letter ISO currency code, in lowercase.
	FixedValueCurrency *string `json:"fixed_value_currency,omitempty"`
	// Use if type is set to fixed. The unit amount in cents to be discounted, represented as a decimal string with at most 12 decimal places.
	FixedValueDecimal *string `json:"fixed_value_decimal,omitempty"`
	Name              string  `json:"name"`
	// Use if type is set to percentage. The percentage to be discounted, represented as a whole integer.
	PercentageValue *string       `json:"percentage_value,omitempty"`
	Prices          *BaseRelation `json:"prices,omitempty"`
	// Map of ids of promo codes with their usage count
	PromoCodeUsage map[string]float64 `json:"promo_code_usage,omitempty"`
	PromoCodes     []PromoCode        `json:"promo_codes,omitempty"`
	// Whether the coupon requires a promo code to be applied
	RequiresPromoCode *bool `json:"requires_promo_code,omitempty"`
	Type              Type  `json:"type"`
}

func (c Coupon) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Coupon) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Coupon) GetAdditional() map[string]any {
	if o == nil {
		return nil
	}
	return o.Additional
}

func (o *Coupon) GetACL() *BaseEntityACL {
	if o == nil {
		return nil
	}
	return o.ACL
}

func (o *Coupon) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *Coupon) GetFiles() *BaseRelation {
	if o == nil {
		return nil
	}
	return o.Files
}

func (o *Coupon) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Coupon) GetManifest() []string {
	if o == nil {
		return nil
	}
	return o.Manifest
}

func (o *Coupon) GetOrg() string {
	if o == nil {
		return ""
	}
	return o.Org
}

func (o *Coupon) GetOwners() []BaseEntityOwner {
	if o == nil {
		return nil
	}
	return o.Owners
}

func (o *Coupon) GetSchema() Schema {
	if o == nil {
		return Schema("")
	}
	return o.Schema
}

func (o *Coupon) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *Coupon) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *Coupon) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *Coupon) GetActive() bool {
	if o == nil {
		return false
	}
	return o.Active
}

func (o *Coupon) GetCashbackPeriod() *CashbackPeriod {
	if o == nil {
		return nil
	}
	return o.CashbackPeriod
}

func (o *Coupon) GetCategory() Category {
	if o == nil {
		return Category("")
	}
	return o.Category
}

func (o *Coupon) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Coupon) GetFixedValue() *float64 {
	if o == nil {
		return nil
	}
	return o.FixedValue
}

func (o *Coupon) GetFixedValueCurrency() *string {
	if o == nil {
		return nil
	}
	return o.FixedValueCurrency
}

func (o *Coupon) GetFixedValueDecimal() *string {
	if o == nil {
		return nil
	}
	return o.FixedValueDecimal
}

func (o *Coupon) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Coupon) GetPercentageValue() *string {
	if o == nil {
		return nil
	}
	return o.PercentageValue
}

func (o *Coupon) GetPrices() *BaseRelation {
	if o == nil {
		return nil
	}
	return o.Prices
}

func (o *Coupon) GetPromoCodeUsage() map[string]float64 {
	if o == nil {
		return nil
	}
	return o.PromoCodeUsage
}

func (o *Coupon) GetPromoCodes() []PromoCode {
	if o == nil {
		return nil
	}
	return o.PromoCodes
}

func (o *Coupon) GetRequiresPromoCode() *bool {
	if o == nil {
		return nil
	}
	return o.RequiresPromoCode
}

func (o *Coupon) GetType() Type {
	if o == nil {
		return Type("")
	}
	return o.Type
}
