// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DataRetrievalItem struct {
	Extension *PublicExtensionDetails         `json:"extension,omitempty"`
	Hook      *PublicDataRetrievalHookDetails `json:"hook,omitempty"`
}

func (o *DataRetrievalItem) GetExtension() *PublicExtensionDetails {
	if o == nil {
		return nil
	}
	return o.Extension
}

func (o *DataRetrievalItem) GetHook() *PublicDataRetrievalHookDetails {
	if o == nil {
		return nil
	}
	return o.Hook
}
