// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/internal/utils"
	"time"
)

type EntityItem struct {
	AdditionalProperties any `additionalProperties:"true" json:"-"`
	// Creation timestamp of the entity
	CreatedAt time.Time `json:"_created_at"`
	// Entity ID
	ID string `json:"_id"`
	// Organization ID the entity belongs to
	Org string `json:"_org"`
	// URL-friendly identifier for the entity schema
	Schema EntitySlug `json:"_schema"`
	// Array of entity tags
	Tags []string `json:"_tags,omitempty"`
	// Title of the entity
	Title string `json:"_title"`
	// Last update timestamp of the entity
	UpdatedAt time.Time `json:"_updated_at"`
}

func (e EntityItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"_created_at", "_id", "_org", "_schema", "_title", "_updated_at"}); err != nil {
		return err
	}
	return nil
}

func (o *EntityItem) GetAdditionalProperties() any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *EntityItem) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *EntityItem) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *EntityItem) GetOrg() string {
	if o == nil {
		return ""
	}
	return o.Org
}

func (o *EntityItem) GetSchema() EntitySlug {
	if o == nil {
		return EntitySlug("")
	}
	return o.Schema
}

func (o *EntityItem) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *EntityItem) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *EntityItem) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
