// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type JuiceSettings struct {
	// Whether the org is in canary mode
	IsCanary *bool `json:"is_canary,omitempty"`
	// Whether the org is in dummy mode
	IsDummy *bool `json:"is_dummy,omitempty"`
}

func (o *JuiceSettings) GetIsCanary() *bool {
	if o == nil {
		return nil
	}
	return o.IsCanary
}

func (o *JuiceSettings) GetIsDummy() *bool {
	if o == nil {
		return nil
	}
	return o.IsDummy
}
