// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/internal/utils"
	"time"
)

type OpportunitySchema string

const (
	OpportunitySchemaOpportunity OpportunitySchema = "opportunity"
)

func (e OpportunitySchema) ToPointer() *OpportunitySchema {
	return &e
}
func (e *OpportunitySchema) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "opportunity":
		*e = OpportunitySchema(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OpportunitySchema: %v", v)
	}
}

// Opportunity - The opportunity entity
type Opportunity struct {
	AdditionalProperties any `additionalProperties:"true" json:"-"`
	// Creation timestamp of the entity
	CreatedAt time.Time `json:"_created_at"`
	// Entity ID
	ID string `json:"_id"`
	// Organization ID the entity belongs to
	Org    string            `json:"_org"`
	Schema OpportunitySchema `json:"_schema"`
	// Array of entity tags
	Tags []string `json:"_tags,omitempty"`
	// Title of the entity
	Title string `json:"_title"`
	// Last update timestamp of the entity
	UpdatedAt time.Time `json:"_updated_at"`
}

func (o Opportunity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *Opportunity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, []string{"_created_at", "_id", "_org", "_schema", "_title", "_updated_at"}); err != nil {
		return err
	}
	return nil
}

func (o *Opportunity) GetAdditionalProperties() any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *Opportunity) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *Opportunity) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Opportunity) GetOrg() string {
	if o == nil {
		return ""
	}
	return o.Org
}

func (o *Opportunity) GetSchema() OpportunitySchema {
	if o == nil {
		return OpportunitySchema("")
	}
	return o.Schema
}

func (o *Opportunity) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *Opportunity) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *Opportunity) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
