// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/internal/utils"
)

type ProductCreateSchema string

const (
	ProductCreateSchemaProduct ProductCreateSchema = "product"
)

func (e ProductCreateSchema) ToPointer() *ProductCreateSchema {
	return &e
}
func (e *ProductCreateSchema) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "product":
		*e = ProductCreateSchema(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProductCreateSchema: %v", v)
	}
}

// ProductCreateType - The type of Product:
//
// | type | description |
// |----| ----|
// | `product` | Represents a physical good |
// | `service` | Represents a service or virtual product |
type ProductCreateType string

const (
	ProductCreateTypeProduct ProductCreateType = "product"
	ProductCreateTypeService ProductCreateType = "service"
)

func (e ProductCreateType) ToPointer() *ProductCreateType {
	return &e
}
func (e *ProductCreateType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "product":
		fallthrough
	case "service":
		*e = ProductCreateType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProductCreateType: %v", v)
	}
}

type ProductCreate struct {
	// Additional fields that are not part of the schema
	Additional        map[string]any `json:"__additional,omitempty"`
	AvailabilityFiles *BaseRelation  `json:"_availability_files,omitempty"`
	Files             *BaseRelation  `json:"_files,omitempty"`
	// Manifest ID used to create/update the entity
	Manifest []string             `json:"_manifest,omitempty"`
	Purpose  []string             `json:"_purpose,omitempty"`
	Schema   *ProductCreateSchema `json:"_schema,omitempty"`
	Tags     []string             `json:"_tags,omitempty"`
	Active   bool                 `json:"active"`
	// The categories of the product
	Categories []string `json:"categories,omitempty"`
	// The product code
	Code *string `json:"code,omitempty"`
	// A description of the product. Multi-line supported.
	Description *string `json:"description,omitempty"`
	Feature     []any   `json:"feature,omitempty"`
	// Not visible to customers, only in internal tables
	InternalName *string `json:"internal_name,omitempty"`
	// The description for the product
	Name             string        `json:"name"`
	PriceOptions     *BaseRelation `json:"price_options,omitempty"`
	ProductDownloads *BaseRelation `json:"product_downloads,omitempty"`
	ProductImages    *BaseRelation `json:"product_images,omitempty"`
	// The type of Product:
	//
	// | type | description |
	// |----| ----|
	// | `product` | Represents a physical good |
	// | `service` | Represents a service or virtual product |
	//
	Type *ProductCreateType `default:"product" json:"type"`
}

func (p ProductCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProductCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ProductCreate) GetAdditional() map[string]any {
	if o == nil {
		return nil
	}
	return o.Additional
}

func (o *ProductCreate) GetAvailabilityFiles() *BaseRelation {
	if o == nil {
		return nil
	}
	return o.AvailabilityFiles
}

func (o *ProductCreate) GetFiles() *BaseRelation {
	if o == nil {
		return nil
	}
	return o.Files
}

func (o *ProductCreate) GetManifest() []string {
	if o == nil {
		return nil
	}
	return o.Manifest
}

func (o *ProductCreate) GetPurpose() []string {
	if o == nil {
		return nil
	}
	return o.Purpose
}

func (o *ProductCreate) GetSchema() *ProductCreateSchema {
	if o == nil {
		return nil
	}
	return o.Schema
}

func (o *ProductCreate) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *ProductCreate) GetActive() bool {
	if o == nil {
		return false
	}
	return o.Active
}

func (o *ProductCreate) GetCategories() []string {
	if o == nil {
		return nil
	}
	return o.Categories
}

func (o *ProductCreate) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *ProductCreate) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *ProductCreate) GetFeature() []any {
	if o == nil {
		return nil
	}
	return o.Feature
}

func (o *ProductCreate) GetInternalName() *string {
	if o == nil {
		return nil
	}
	return o.InternalName
}

func (o *ProductCreate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ProductCreate) GetPriceOptions() *BaseRelation {
	if o == nil {
		return nil
	}
	return o.PriceOptions
}

func (o *ProductCreate) GetProductDownloads() *BaseRelation {
	if o == nil {
		return nil
	}
	return o.ProductDownloads
}

func (o *ProductCreate) GetProductImages() *BaseRelation {
	if o == nil {
		return nil
	}
	return o.ProductImages
}

func (o *ProductCreate) GetType() *ProductCreateType {
	if o == nil {
		return nil
	}
	return o.Type
}
