// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/internal/utils"
)

type Schema struct {
	AdditionalProperties any `additionalProperties:"true" json:"-"`
	// Slug of the schema
	Slug *string `json:"slug,omitempty"`
}

func (s Schema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Schema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *Schema) GetAdditionalProperties() any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}

func (o *Schema) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}
