// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type UpsertPortalConfigV3AdvancedMfa struct {
	// Advanced MFA feature flag
	Enabled *bool `json:"enabled,omitempty"`
}

func (o *UpsertPortalConfigV3AdvancedMfa) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

type UpsertPortalConfigV3EntryPoint string

const (
	UpsertPortalConfigV3EntryPointPassword UpsertPortalConfigV3EntryPoint = "PASSWORD"
	UpsertPortalConfigV3EntryPointSso      UpsertPortalConfigV3EntryPoint = "SSO"
)

func (e UpsertPortalConfigV3EntryPoint) ToPointer() *UpsertPortalConfigV3EntryPoint {
	return &e
}
func (e *UpsertPortalConfigV3EntryPoint) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PASSWORD":
		fallthrough
	case "SSO":
		*e = UpsertPortalConfigV3EntryPoint(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpsertPortalConfigV3EntryPoint: %v", v)
	}
}

type UpsertPortalConfigV3PasswordlessLogin struct {
	// Passwordless login feature flag
	Enabled *bool `json:"enabled,omitempty"`
}

func (o *UpsertPortalConfigV3PasswordlessLogin) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

// UpsertPortalConfigV3AuthSettings - Authentication settings for the portal
type UpsertPortalConfigV3AuthSettings struct {
	// Decide whether to automatically redirect to the provider page during login, which would completely bypass showing the portal authentication page.
	AutoRedirectToSso     *bool                                  `json:"auto_redirect_to_sso,omitempty"`
	EntryPoint            *UpsertPortalConfigV3EntryPoint        `json:"entry_point,omitempty"`
	PasswordlessLogin     *UpsertPortalConfigV3PasswordlessLogin `json:"passwordless_login,omitempty"`
	PreferredSsoProviders []string                               `json:"preferred_sso_providers,omitempty"`
}

func (o *UpsertPortalConfigV3AuthSettings) GetAutoRedirectToSso() *bool {
	if o == nil {
		return nil
	}
	return o.AutoRedirectToSso
}

func (o *UpsertPortalConfigV3AuthSettings) GetEntryPoint() *UpsertPortalConfigV3EntryPoint {
	if o == nil {
		return nil
	}
	return o.EntryPoint
}

func (o *UpsertPortalConfigV3AuthSettings) GetPasswordlessLogin() *UpsertPortalConfigV3PasswordlessLogin {
	if o == nil {
		return nil
	}
	return o.PasswordlessLogin
}

func (o *UpsertPortalConfigV3AuthSettings) GetPreferredSsoProviders() []string {
	if o == nil {
		return nil
	}
	return o.PreferredSsoProviders
}

// UpsertPortalConfigV3PasswordPolicy - Password policy for the portal
type UpsertPortalConfigV3PasswordPolicy struct {
	// Minimum password length
	MinimumLength *int64 `json:"minimum_length,omitempty"`
	// Require lowercase characters
	RequireLowercase *bool `json:"require_lowercase,omitempty"`
	// Require numbers
	RequireNumbers *bool `json:"require_numbers,omitempty"`
	// Require symbols
	RequireSymbols *bool `json:"require_symbols,omitempty"`
	// Require uppercase characters
	RequireUppercase *bool `json:"require_uppercase,omitempty"`
}

func (o *UpsertPortalConfigV3PasswordPolicy) GetMinimumLength() *int64 {
	if o == nil {
		return nil
	}
	return o.MinimumLength
}

func (o *UpsertPortalConfigV3PasswordPolicy) GetRequireLowercase() *bool {
	if o == nil {
		return nil
	}
	return o.RequireLowercase
}

func (o *UpsertPortalConfigV3PasswordPolicy) GetRequireNumbers() *bool {
	if o == nil {
		return nil
	}
	return o.RequireNumbers
}

func (o *UpsertPortalConfigV3PasswordPolicy) GetRequireSymbols() *bool {
	if o == nil {
		return nil
	}
	return o.RequireSymbols
}

func (o *UpsertPortalConfigV3PasswordPolicy) GetRequireUppercase() *bool {
	if o == nil {
		return nil
	}
	return o.RequireUppercase
}

// UpsertPortalConfigV3CognitoDetails - AWS Cognito Pool details for the portal
type UpsertPortalConfigV3CognitoDetails struct {
	// Cognito user pool ARN
	CognitoUserPoolArn *string `json:"cognito_user_pool_arn,omitempty"`
	// Cognito user pool client ID
	CognitoUserPoolClientID *string `json:"cognito_user_pool_client_id,omitempty"`
	// Cognito user pool ID
	CognitoUserPoolID *string `json:"cognito_user_pool_id,omitempty"`
	// Password policy for the portal
	PasswordPolicy *UpsertPortalConfigV3PasswordPolicy `json:"password_policy,omitempty"`
}

func (o *UpsertPortalConfigV3CognitoDetails) GetCognitoUserPoolArn() *string {
	if o == nil {
		return nil
	}
	return o.CognitoUserPoolArn
}

func (o *UpsertPortalConfigV3CognitoDetails) GetCognitoUserPoolClientID() *string {
	if o == nil {
		return nil
	}
	return o.CognitoUserPoolClientID
}

func (o *UpsertPortalConfigV3CognitoDetails) GetCognitoUserPoolID() *string {
	if o == nil {
		return nil
	}
	return o.CognitoUserPoolID
}

func (o *UpsertPortalConfigV3CognitoDetails) GetPasswordPolicy() *UpsertPortalConfigV3PasswordPolicy {
	if o == nil {
		return nil
	}
	return o.PasswordPolicy
}

// UpsertPortalConfigV3ContractSelectorConfig - Configuration for contract selector in the portal
type UpsertPortalConfigV3ContractSelectorConfig struct {
	// Whether to show inactive contracts in the selector
	ShowInactive *bool `json:"show_inactive,omitempty"`
	// Path to the property to use as the contract title
	TitlePath *string `json:"title_path,omitempty"`
}

func (o *UpsertPortalConfigV3ContractSelectorConfig) GetShowInactive() *bool {
	if o == nil {
		return nil
	}
	return o.ShowInactive
}

func (o *UpsertPortalConfigV3ContractSelectorConfig) GetTitlePath() *string {
	if o == nil {
		return nil
	}
	return o.TitlePath
}

// UpsertPortalConfigV3DefaultUserToNotify - Default 360 user to notify upon an internal notification
type UpsertPortalConfigV3DefaultUserToNotify struct {
	// Default admin users for pending user notification to notify
	OnPendingUser []AdminUser `json:"onPendingUser,omitempty"`
}

func (o *UpsertPortalConfigV3DefaultUserToNotify) GetOnPendingUser() []AdminUser {
	if o == nil {
		return nil
	}
	return o.OnPendingUser
}

type UpsertPortalConfigV3ActionLabel struct {
	De *string `json:"de,omitempty"`
	En *string `json:"en,omitempty"`
}

func (o *UpsertPortalConfigV3ActionLabel) GetDe() *string {
	if o == nil {
		return nil
	}
	return o.De
}

func (o *UpsertPortalConfigV3ActionLabel) GetEn() *string {
	if o == nil {
		return nil
	}
	return o.En
}

type UpsertPortalConfigV3EntityActions struct {
	ActionLabel *UpsertPortalConfigV3ActionLabel `json:"action_Label,omitempty"`
	// Entity ID
	JourneyID *string `json:"journey_id,omitempty"`
	// URL-friendly identifier for the entity schema
	Slug *EntitySlug `json:"slug,omitempty"`
}

func (o *UpsertPortalConfigV3EntityActions) GetActionLabel() *UpsertPortalConfigV3ActionLabel {
	if o == nil {
		return nil
	}
	return o.ActionLabel
}

func (o *UpsertPortalConfigV3EntityActions) GetJourneyID() *string {
	if o == nil {
		return nil
	}
	return o.JourneyID
}

func (o *UpsertPortalConfigV3EntityActions) GetSlug() *EntitySlug {
	if o == nil {
		return nil
	}
	return o.Slug
}

type UpsertPortalConfigV3CadencePeriodType string

const (
	UpsertPortalConfigV3CadencePeriodTypeDays   UpsertPortalConfigV3CadencePeriodType = "days"
	UpsertPortalConfigV3CadencePeriodTypeWeeks  UpsertPortalConfigV3CadencePeriodType = "weeks"
	UpsertPortalConfigV3CadencePeriodTypeMonths UpsertPortalConfigV3CadencePeriodType = "months"
)

func (e UpsertPortalConfigV3CadencePeriodType) ToPointer() *UpsertPortalConfigV3CadencePeriodType {
	return &e
}
func (e *UpsertPortalConfigV3CadencePeriodType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "days":
		fallthrough
	case "weeks":
		fallthrough
	case "months":
		*e = UpsertPortalConfigV3CadencePeriodType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpsertPortalConfigV3CadencePeriodType: %v", v)
	}
}

type UpsertPortalConfigV3RuleType string

const (
	UpsertPortalConfigV3RuleTypeCadence                UpsertPortalConfigV3RuleType = "cadence"
	UpsertPortalConfigV3RuleTypeRelativeToCurrentValue UpsertPortalConfigV3RuleType = "relative_to_current_value"
	UpsertPortalConfigV3RuleTypeDaysBeforeDate         UpsertPortalConfigV3RuleType = "days_before_date"
	UpsertPortalConfigV3RuleTypeOverduePayments        UpsertPortalConfigV3RuleType = "overdue_payments"
)

func (e UpsertPortalConfigV3RuleType) ToPointer() *UpsertPortalConfigV3RuleType {
	return &e
}
func (e *UpsertPortalConfigV3RuleType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "cadence":
		fallthrough
	case "relative_to_current_value":
		fallthrough
	case "days_before_date":
		fallthrough
	case "overdue_payments":
		*e = UpsertPortalConfigV3RuleType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpsertPortalConfigV3RuleType: %v", v)
	}
}

type UpsertPortalConfigV3EntityEditRules struct {
	AllowedDecrement              *string                                `json:"allowed_decrement,omitempty"`
	AllowedIncrement              *string                                `json:"allowed_increment,omitempty"`
	Attribute                     *string                                `json:"attribute,omitempty"`
	CadencePeriod                 *float64                               `json:"cadence_period,omitempty"`
	CadencePeriodType             *UpsertPortalConfigV3CadencePeriodType `json:"cadence_period_type,omitempty"`
	ChangesAllowed                *int64                                 `json:"changes_allowed,omitempty"`
	GracePeriod                   *int64                                 `json:"grace_period,omitempty"`
	NumberOfDaysBeforeRestriction *int64                                 `json:"number_of_days_before_restriction,omitempty"`
	RuleType                      *UpsertPortalConfigV3RuleType          `json:"rule_type,omitempty"`
	// URL-friendly identifier for the entity schema
	Slug *EntitySlug `json:"slug,omitempty"`
}

func (o *UpsertPortalConfigV3EntityEditRules) GetAllowedDecrement() *string {
	if o == nil {
		return nil
	}
	return o.AllowedDecrement
}

func (o *UpsertPortalConfigV3EntityEditRules) GetAllowedIncrement() *string {
	if o == nil {
		return nil
	}
	return o.AllowedIncrement
}

func (o *UpsertPortalConfigV3EntityEditRules) GetAttribute() *string {
	if o == nil {
		return nil
	}
	return o.Attribute
}

func (o *UpsertPortalConfigV3EntityEditRules) GetCadencePeriod() *float64 {
	if o == nil {
		return nil
	}
	return o.CadencePeriod
}

func (o *UpsertPortalConfigV3EntityEditRules) GetCadencePeriodType() *UpsertPortalConfigV3CadencePeriodType {
	if o == nil {
		return nil
	}
	return o.CadencePeriodType
}

func (o *UpsertPortalConfigV3EntityEditRules) GetChangesAllowed() *int64 {
	if o == nil {
		return nil
	}
	return o.ChangesAllowed
}

func (o *UpsertPortalConfigV3EntityEditRules) GetGracePeriod() *int64 {
	if o == nil {
		return nil
	}
	return o.GracePeriod
}

func (o *UpsertPortalConfigV3EntityEditRules) GetNumberOfDaysBeforeRestriction() *int64 {
	if o == nil {
		return nil
	}
	return o.NumberOfDaysBeforeRestriction
}

func (o *UpsertPortalConfigV3EntityEditRules) GetRuleType() *UpsertPortalConfigV3RuleType {
	if o == nil {
		return nil
	}
	return o.RuleType
}

func (o *UpsertPortalConfigV3EntityEditRules) GetSlug() *EntitySlug {
	if o == nil {
		return nil
	}
	return o.Slug
}

type UpsertPortalConfigV3Type struct {
	// Attributes used to identify an entity
	Attributes []string `json:"attributes,omitempty"`
	// Enable/Disable the entity identifier
	IsEnabled *bool `json:"isEnabled,omitempty"`
}

func (o *UpsertPortalConfigV3Type) GetAttributes() []string {
	if o == nil {
		return nil
	}
	return o.Attributes
}

func (o *UpsertPortalConfigV3Type) GetIsEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.IsEnabled
}

// UpsertPortalConfigV3EntityIdentifiers - Identifiers used to identify an entity by a portal user. Deprecated. Use contract_identifiers instead.
//
// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
type UpsertPortalConfigV3EntityIdentifiers struct {
	Type *UpsertPortalConfigV3Type `json:"type,omitempty"`
}

func (o *UpsertPortalConfigV3EntityIdentifiers) GetType() *UpsertPortalConfigV3Type {
	if o == nil {
		return nil
	}
	return o.Type
}

// UpsertPortalConfigV3FeatureSettings - Feature settings for the portal
type UpsertPortalConfigV3FeatureSettings struct {
	// Billing feature flag
	Billing *bool `json:"billing,omitempty"`
	// Change due date feature flag
	ChangeDueDate *bool `json:"change_due_date,omitempty"`
	// Enable or disable the new design for the portal
	NewDesign *bool `json:"new_design,omitempty"`
	// Start page feature flag
	StartPage *bool `json:"start_page,omitempty"`
}

func (o *UpsertPortalConfigV3FeatureSettings) GetBilling() *bool {
	if o == nil {
		return nil
	}
	return o.Billing
}

func (o *UpsertPortalConfigV3FeatureSettings) GetChangeDueDate() *bool {
	if o == nil {
		return nil
	}
	return o.ChangeDueDate
}

func (o *UpsertPortalConfigV3FeatureSettings) GetNewDesign() *bool {
	if o == nil {
		return nil
	}
	return o.NewDesign
}

func (o *UpsertPortalConfigV3FeatureSettings) GetStartPage() *bool {
	if o == nil {
		return nil
	}
	return o.StartPage
}

// UpsertPortalConfigV3Images - Teaser & Banner Image web links
type UpsertPortalConfigV3Images struct {
	// URL of the order left teaser image
	OrderLeftTeaser *string `json:"orderLeftTeaser,omitempty"`
	// URL of the order right teaser image
	OrderRightTeaser *string `json:"orderRightTeaser,omitempty"`
	// URL of the welcome banner image
	WelcomeBanner *string `json:"welcomeBanner,omitempty"`
}

func (o *UpsertPortalConfigV3Images) GetOrderLeftTeaser() *string {
	if o == nil {
		return nil
	}
	return o.OrderLeftTeaser
}

func (o *UpsertPortalConfigV3Images) GetOrderRightTeaser() *string {
	if o == nil {
		return nil
	}
	return o.OrderRightTeaser
}

func (o *UpsertPortalConfigV3Images) GetWelcomeBanner() *string {
	if o == nil {
		return nil
	}
	return o.WelcomeBanner
}

type UpsertPortalConfigV3SelfRegistrationSetting string

const (
	UpsertPortalConfigV3SelfRegistrationSettingAllowWithContactCreation    UpsertPortalConfigV3SelfRegistrationSetting = "ALLOW_WITH_CONTACT_CREATION"
	UpsertPortalConfigV3SelfRegistrationSettingAllowWithoutContactCreation UpsertPortalConfigV3SelfRegistrationSetting = "ALLOW_WITHOUT_CONTACT_CREATION"
	UpsertPortalConfigV3SelfRegistrationSettingDeny                        UpsertPortalConfigV3SelfRegistrationSetting = "DENY"
)

func (e UpsertPortalConfigV3SelfRegistrationSetting) ToPointer() *UpsertPortalConfigV3SelfRegistrationSetting {
	return &e
}
func (e *UpsertPortalConfigV3SelfRegistrationSetting) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ALLOW_WITH_CONTACT_CREATION":
		fallthrough
	case "ALLOW_WITHOUT_CONTACT_CREATION":
		fallthrough
	case "DENY":
		*e = UpsertPortalConfigV3SelfRegistrationSetting(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpsertPortalConfigV3SelfRegistrationSetting: %v", v)
	}
}

type UpsertPortalConfigV3TriggerName string

const (
	UpsertPortalConfigV3TriggerNameFirstLogin   UpsertPortalConfigV3TriggerName = "FIRST_LOGIN"
	UpsertPortalConfigV3TriggerNameAcceptOrder  UpsertPortalConfigV3TriggerName = "ACCEPT_ORDER"
	UpsertPortalConfigV3TriggerNameDeclineOrder UpsertPortalConfigV3TriggerName = "DECLINE_ORDER"
)

func (e UpsertPortalConfigV3TriggerName) ToPointer() *UpsertPortalConfigV3TriggerName {
	return &e
}
func (e *UpsertPortalConfigV3TriggerName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "FIRST_LOGIN":
		fallthrough
	case "ACCEPT_ORDER":
		fallthrough
	case "DECLINE_ORDER":
		*e = UpsertPortalConfigV3TriggerName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpsertPortalConfigV3TriggerName: %v", v)
	}
}

type UpsertPortalConfigV3TriggeredJourneys struct {
	// Entity ID
	JourneyID   *string                          `json:"journey_id,omitempty"`
	TriggerName *UpsertPortalConfigV3TriggerName `json:"trigger_name,omitempty"`
}

func (o *UpsertPortalConfigV3TriggeredJourneys) GetJourneyID() *string {
	if o == nil {
		return nil
	}
	return o.JourneyID
}

func (o *UpsertPortalConfigV3TriggeredJourneys) GetTriggerName() *UpsertPortalConfigV3TriggerName {
	if o == nil {
		return nil
	}
	return o.TriggerName
}

type UpsertPortalConfigV3 struct {
	// Access token for the portal
	AccessToken *string                          `json:"accessToken,omitempty"`
	AdvancedMfa *UpsertPortalConfigV3AdvancedMfa `json:"advanced_mfa,omitempty"`
	// Allowed file extensions for upload
	AllowedFileExtensions   *AllowedFileExtensions `json:"allowed_file_extensions,omitempty"`
	ApprovalStateAttributes map[string][]string    `json:"approval_state_attributes,omitempty"`
	// Authentication settings for the portal
	AuthSettings *UpsertPortalConfigV3AuthSettings `json:"auth_settings,omitempty"`
	// AWS Cognito Pool details for the portal
	CognitoDetails *UpsertPortalConfigV3CognitoDetails `json:"cognito_details,omitempty"`
	// Stringified object with configuration details
	Config *string `json:"config,omitempty"`
	// Deprecated. Use registration_identifiers instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ContactIdentifiers []string `json:"contact_identifiers,omitempty"`
	// Identifiers to identify a contract by a portal user.
	ContractIdentifiers []ContractIdentifier `json:"contract_identifiers,omitempty"`
	// Configuration for contract selector in the portal
	ContractSelectorConfig *UpsertPortalConfigV3ContractSelectorConfig `json:"contract_selector_config,omitempty"`
	// Default 360 user to notify upon an internal notification
	DefaultUserToNotify *UpsertPortalConfigV3DefaultUserToNotify `json:"default_user_to_notify,omitempty"`
	// Entity ID
	DesignID *string `json:"design_id,omitempty"`
	// The URL on which the portal is accessible
	Domain *string `json:"domain,omitempty"`
	// Email templates used for authentication and internal processes
	EmailTemplates *EmailTemplates `json:"email_templates,omitempty"`
	// Enable/Disable the portal access
	Enabled *bool `json:"enabled,omitempty"`
	// Journey actions allowed on an entity by a portal user
	EntityActions []UpsertPortalConfigV3EntityActions `json:"entity_actions,omitempty"`
	// Rules for editing an entity by a portal user
	EntityEditRules []UpsertPortalConfigV3EntityEditRules `json:"entity_edit_rules,omitempty"`
	// Identifiers used to identify an entity by a portal user. Deprecated. Use contract_identifiers instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	EntityIdentifiers *UpsertPortalConfigV3EntityIdentifiers `json:"entity_identifiers,omitempty"`
	// Configured Portal extensions hooks
	ExtensionHooks map[string]*ExtensionHookConfig `json:"extension_hooks,omitempty"`
	// Configured Portal extensions
	Extensions []ExtensionConfig `json:"extensions,omitempty"`
	// Feature settings for the portal
	FeatureSettings *UpsertPortalConfigV3FeatureSettings `json:"feature_settings,omitempty"`
	// Teaser & Banner Image web links
	Images *UpsertPortalConfigV3Images `json:"images,omitempty"`
	// Number of years to look back for showing inactive contracts in the portal
	InactiveContractCutoffYears *float64 `json:"inactive_contract_cutoff_years,omitempty"`
	// Whether this is a dummy/test portal configuration
	IsDummy *bool `json:"is_dummy,omitempty"`
	// Mark true if the domain is an Epilot domain
	IsEpilotDomain *bool `json:"is_epilot_domain,omitempty"`
	// Whether this is a v3 portal configuration
	IsV3Item *bool `json:"is_v3_item,omitempty"`
	// Grace period in days for meter readings
	MeterReadingGracePeriod *float64 `json:"meter_reading_grace_period,omitempty"`
	// A short name to identify your portal
	Name *string `json:"name,omitempty"`
	// Origin of the portal
	Origin *string       `json:"origin,omitempty"`
	Pages  []PageRequest `json:"pages,omitempty"`
	// ID of the portal
	PortalID *string `json:"portal_id,omitempty"`
	// Key of the portal config
	PortalSkV3 *string `json:"portal_sk_v3,omitempty"`
	// Prevent indexing by search engines
	PreventSearchEngineIndexing *bool `json:"prevent_search_engine_indexing,omitempty"`
	// Identifiers to identify a contact of a portal user during the registration.
	RegistrationIdentifiers []ContractIdentifier                         `json:"registration_identifiers,omitempty"`
	SelfRegistrationSetting *UpsertPortalConfigV3SelfRegistrationSetting `json:"self_registration_setting,omitempty"`
	// Journeys automatically opened on a portal user action
	TriggeredJourneys []UpsertPortalConfigV3TriggeredJourneys `json:"triggered_journeys,omitempty"`
}

func (o *UpsertPortalConfigV3) GetAccessToken() *string {
	if o == nil {
		return nil
	}
	return o.AccessToken
}

func (o *UpsertPortalConfigV3) GetAdvancedMfa() *UpsertPortalConfigV3AdvancedMfa {
	if o == nil {
		return nil
	}
	return o.AdvancedMfa
}

func (o *UpsertPortalConfigV3) GetAllowedFileExtensions() *AllowedFileExtensions {
	if o == nil {
		return nil
	}
	return o.AllowedFileExtensions
}

func (o *UpsertPortalConfigV3) GetApprovalStateAttributes() map[string][]string {
	if o == nil {
		return nil
	}
	return o.ApprovalStateAttributes
}

func (o *UpsertPortalConfigV3) GetAuthSettings() *UpsertPortalConfigV3AuthSettings {
	if o == nil {
		return nil
	}
	return o.AuthSettings
}

func (o *UpsertPortalConfigV3) GetCognitoDetails() *UpsertPortalConfigV3CognitoDetails {
	if o == nil {
		return nil
	}
	return o.CognitoDetails
}

func (o *UpsertPortalConfigV3) GetConfig() *string {
	if o == nil {
		return nil
	}
	return o.Config
}

func (o *UpsertPortalConfigV3) GetContactIdentifiers() []string {
	if o == nil {
		return nil
	}
	return o.ContactIdentifiers
}

func (o *UpsertPortalConfigV3) GetContractIdentifiers() []ContractIdentifier {
	if o == nil {
		return nil
	}
	return o.ContractIdentifiers
}

func (o *UpsertPortalConfigV3) GetContractSelectorConfig() *UpsertPortalConfigV3ContractSelectorConfig {
	if o == nil {
		return nil
	}
	return o.ContractSelectorConfig
}

func (o *UpsertPortalConfigV3) GetDefaultUserToNotify() *UpsertPortalConfigV3DefaultUserToNotify {
	if o == nil {
		return nil
	}
	return o.DefaultUserToNotify
}

func (o *UpsertPortalConfigV3) GetDesignID() *string {
	if o == nil {
		return nil
	}
	return o.DesignID
}

func (o *UpsertPortalConfigV3) GetDomain() *string {
	if o == nil {
		return nil
	}
	return o.Domain
}

func (o *UpsertPortalConfigV3) GetEmailTemplates() *EmailTemplates {
	if o == nil {
		return nil
	}
	return o.EmailTemplates
}

func (o *UpsertPortalConfigV3) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *UpsertPortalConfigV3) GetEntityActions() []UpsertPortalConfigV3EntityActions {
	if o == nil {
		return nil
	}
	return o.EntityActions
}

func (o *UpsertPortalConfigV3) GetEntityEditRules() []UpsertPortalConfigV3EntityEditRules {
	if o == nil {
		return nil
	}
	return o.EntityEditRules
}

func (o *UpsertPortalConfigV3) GetEntityIdentifiers() *UpsertPortalConfigV3EntityIdentifiers {
	if o == nil {
		return nil
	}
	return o.EntityIdentifiers
}

func (o *UpsertPortalConfigV3) GetExtensionHooks() map[string]*ExtensionHookConfig {
	if o == nil {
		return nil
	}
	return o.ExtensionHooks
}

func (o *UpsertPortalConfigV3) GetExtensions() []ExtensionConfig {
	if o == nil {
		return nil
	}
	return o.Extensions
}

func (o *UpsertPortalConfigV3) GetFeatureSettings() *UpsertPortalConfigV3FeatureSettings {
	if o == nil {
		return nil
	}
	return o.FeatureSettings
}

func (o *UpsertPortalConfigV3) GetImages() *UpsertPortalConfigV3Images {
	if o == nil {
		return nil
	}
	return o.Images
}

func (o *UpsertPortalConfigV3) GetInactiveContractCutoffYears() *float64 {
	if o == nil {
		return nil
	}
	return o.InactiveContractCutoffYears
}

func (o *UpsertPortalConfigV3) GetIsDummy() *bool {
	if o == nil {
		return nil
	}
	return o.IsDummy
}

func (o *UpsertPortalConfigV3) GetIsEpilotDomain() *bool {
	if o == nil {
		return nil
	}
	return o.IsEpilotDomain
}

func (o *UpsertPortalConfigV3) GetIsV3Item() *bool {
	if o == nil {
		return nil
	}
	return o.IsV3Item
}

func (o *UpsertPortalConfigV3) GetMeterReadingGracePeriod() *float64 {
	if o == nil {
		return nil
	}
	return o.MeterReadingGracePeriod
}

func (o *UpsertPortalConfigV3) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpsertPortalConfigV3) GetOrigin() *string {
	if o == nil {
		return nil
	}
	return o.Origin
}

func (o *UpsertPortalConfigV3) GetPages() []PageRequest {
	if o == nil {
		return nil
	}
	return o.Pages
}

func (o *UpsertPortalConfigV3) GetPortalID() *string {
	if o == nil {
		return nil
	}
	return o.PortalID
}

func (o *UpsertPortalConfigV3) GetPortalSkV3() *string {
	if o == nil {
		return nil
	}
	return o.PortalSkV3
}

func (o *UpsertPortalConfigV3) GetPreventSearchEngineIndexing() *bool {
	if o == nil {
		return nil
	}
	return o.PreventSearchEngineIndexing
}

func (o *UpsertPortalConfigV3) GetRegistrationIdentifiers() []ContractIdentifier {
	if o == nil {
		return nil
	}
	return o.RegistrationIdentifiers
}

func (o *UpsertPortalConfigV3) GetSelfRegistrationSetting() *UpsertPortalConfigV3SelfRegistrationSetting {
	if o == nil {
		return nil
	}
	return o.SelfRegistrationSetting
}

func (o *UpsertPortalConfigV3) GetTriggeredJourneys() []UpsertPortalConfigV3TriggeredJourneys {
	if o == nil {
		return nil
	}
	return o.TriggeredJourneys
}
