workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://docs.api.epilot.io/product.yaml
        registry:
            location: registry.speakeasyapi.dev/epilot/epilot/my-source
targets:
    terraform:
        target: terraform
        source: my-source
