// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/provider/typeconvert"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-product/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-product/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *ProductRecommendationDataSourceModel) RefreshFromSharedProductRecommendation(ctx context.Context, resp *shared.ProductRecommendation) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.Additional != nil {
			r.Additional = make(map[string]jsontypes.Normalized, len(resp.Additional))
			for key, value := range resp.Additional {
				result, _ := json.Marshal(value)
				r.Additional[key] = jsontypes.NewNormalizedValue(string(result))
			}
		}
		if resp.ACL == nil {
			r.ACL = nil
		} else {
			r.ACL = &tfTypes.BaseEntityACL{}
			r.ACL.Delete = make([]types.String, 0, len(resp.ACL.Delete))
			for _, v := range resp.ACL.Delete {
				r.ACL.Delete = append(r.ACL.Delete, types.StringValue(v))
			}
			r.ACL.Edit = make([]types.String, 0, len(resp.ACL.Edit))
			for _, v := range resp.ACL.Edit {
				r.ACL.Edit = append(r.ACL.Edit, types.StringValue(v))
			}
			r.ACL.View = make([]types.String, 0, len(resp.ACL.View))
			for _, v := range resp.ACL.View {
				r.ACL.View = append(r.ACL.View, types.StringValue(v))
			}
		}
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		if resp.Files == nil {
			r.Files = nil
		} else {
			r.Files = &tfTypes.BaseRelation{}
			r.Files.DollarRelation = []tfTypes.DollarRelation{}

			for _, dollarRelationItem := range resp.Files.DollarRelation {
				var dollarRelation tfTypes.DollarRelation

				if dollarRelationItem.Tags != nil {
					dollarRelation.Tags = make([]types.String, 0, len(dollarRelationItem.Tags))
					for _, v := range dollarRelationItem.Tags {
						dollarRelation.Tags = append(dollarRelation.Tags, types.StringValue(v))
					}
				}
				dollarRelation.EntityID = types.StringPointerValue(dollarRelationItem.EntityID)

				r.Files.DollarRelation = append(r.Files.DollarRelation, dollarRelation)
			}
		}
		r.ID = types.StringPointerValue(resp.ID)
		r.Manifest = make([]types.String, 0, len(resp.Manifest))
		for _, v := range resp.Manifest {
			r.Manifest = append(r.Manifest, types.StringValue(v))
		}
		r.Org = types.StringValue(resp.Org)
		r.Owners = []tfTypes.BaseEntityOwner{}

		for _, ownersItem := range resp.Owners {
			var owners tfTypes.BaseEntityOwner

			owners.OrgID = types.StringValue(ownersItem.OrgID)
			owners.UserID = types.StringPointerValue(ownersItem.UserID)

			r.Owners = append(r.Owners, owners)
		}
		if resp.Purpose != nil {
			r.Purpose = make([]types.String, 0, len(resp.Purpose))
			for _, v := range resp.Purpose {
				r.Purpose = append(r.Purpose, types.StringValue(v))
			}
		}
		r.Schema = types.StringValue(string(resp.Schema))
		if resp.Tags != nil {
			r.Tags = make([]types.String, 0, len(resp.Tags))
			for _, v := range resp.Tags {
				r.Tags = append(r.Tags, types.StringValue(v))
			}
		}
		r.Title = types.StringPointerValue(resp.Title)
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
		r.Offers = []tfTypes.Offer{}

		for _, offersItem := range resp.Offers {
			var offers tfTypes.Offer

			offers.PriceID = types.StringPointerValue(offersItem.PriceID)
			offers.ProductID = types.StringPointerValue(offersItem.ProductID)
			offers.TargetID = types.StringPointerValue(offersItem.TargetID)

			r.Offers = append(r.Offers, offers)
		}
		if resp.SourcePrice == nil {
			r.SourcePrice = nil
		} else {
			r.SourcePrice = &tfTypes.ProductRecommendationCreateSourcePrice{}
			r.SourcePrice.DollarRelation = []tfTypes.BaseRelation{}

			for _, dollarRelationItem1 := range resp.SourcePrice.DollarRelation {
				var dollarRelation1 tfTypes.BaseRelation

				dollarRelation1.DollarRelation = []tfTypes.DollarRelation{}

				for _, dollarRelationItem2 := range dollarRelationItem1.DollarRelation {
					var dollarRelation2 tfTypes.DollarRelation

					if dollarRelationItem2.Tags != nil {
						dollarRelation2.Tags = make([]types.String, 0, len(dollarRelationItem2.Tags))
						for _, v := range dollarRelationItem2.Tags {
							dollarRelation2.Tags = append(dollarRelation2.Tags, types.StringValue(v))
						}
					}
					dollarRelation2.EntityID = types.StringPointerValue(dollarRelationItem2.EntityID)

					dollarRelation1.DollarRelation = append(dollarRelation1.DollarRelation, dollarRelation2)
				}

				r.SourcePrice.DollarRelation = append(r.SourcePrice.DollarRelation, dollarRelation1)
			}
		}
		if resp.SourceProduct == nil {
			r.SourceProduct = nil
		} else {
			r.SourceProduct = &tfTypes.ProductRecommendationCreateSourcePrice{}
			r.SourceProduct.DollarRelation = []tfTypes.BaseRelation{}

			for _, dollarRelationItem3 := range resp.SourceProduct.DollarRelation {
				var dollarRelation3 tfTypes.BaseRelation

				dollarRelation3.DollarRelation = []tfTypes.DollarRelation{}

				for _, dollarRelationItem4 := range dollarRelationItem3.DollarRelation {
					var dollarRelation4 tfTypes.DollarRelation

					if dollarRelationItem4.Tags != nil {
						dollarRelation4.Tags = make([]types.String, 0, len(dollarRelationItem4.Tags))
						for _, v := range dollarRelationItem4.Tags {
							dollarRelation4.Tags = append(dollarRelation4.Tags, types.StringValue(v))
						}
					}
					dollarRelation4.EntityID = types.StringPointerValue(dollarRelationItem4.EntityID)

					dollarRelation3.DollarRelation = append(dollarRelation3.DollarRelation, dollarRelation4)
				}

				r.SourceProduct.DollarRelation = append(r.SourceProduct.DollarRelation, dollarRelation3)
			}
		}
		r.Type = types.StringValue(string(resp.Type))
	}

	return diags
}

func (r *ProductRecommendationDataSourceModel) ToOperationsGetProductRecommendationRequest(ctx context.Context) (*operations.GetProductRecommendationRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	hydrate := new(bool)
	if !r.Hydrate.IsUnknown() && !r.Hydrate.IsNull() {
		*hydrate = r.Hydrate.ValueBool()
	} else {
		hydrate = nil
	}
	var productRecommendationID string
	productRecommendationID = r.ID.ValueString()

	strict := new(bool)
	if !r.Strict.IsUnknown() && !r.Strict.IsNull() {
		*strict = r.Strict.ValueBool()
	} else {
		strict = nil
	}
	out := operations.GetProductRecommendationRequest{
		Hydrate:                 hydrate,
		ProductRecommendationID: productRecommendationID,
		Strict:                  strict,
	}

	return &out, diags
}
